name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Socialeap
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          
          # Lines of Code Plugin
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          
          # Language Details
          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_ignored: html, css
          
          # Activity (Filtered to prevent timeout errors)
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: issue, pr, release, member
          
          # Technical adjustments for high-volume accounts
          config_padding: 0, 8 + 11%
          delay: 120
